Django_prg/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('',include('single_pages.urls')),
    path('exam/',include('exam.urls')),
    path('accounts/', include('allauth.urls')), # logout눌렀을때 페이지 allauth가 처리를 해주고 있음.
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    # 이 부분을 채울 예정!
    path('search/<str:q>/',views.PostSearch.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/',views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/',views.delete_comment),
    path('',views.PostList.as_view()),
    # path('', views.index),
    path('<int:pk>/',views.PostDetail.as_view()), # pk는 변수
    # path('<int:pk>/', views.single_post_page),
    path('category/<str:slug>/', views.category_page), # category_page 함수 호출   as_view가 있으면 class 없으면 함수.
    path('create_post/',views.PostCreate.as_view()), # PostCreate 클래스를 참조해라.
    path('update_post/<int:pk>/',views.PostUpdate.as_view()),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

from django.shortcuts import render


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)  # allow unicode= 한글도 가능하게
    def __str__(self):
        return self.name


class Category(models.Model):  # DB table
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)  # allow unicode= 한글도 가능하게

    # slug: 주요단어 뽑아내는 것.(제목화 될수 있는것들) html코드로만 쓸수 있는거만 가능

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'  # 테이블에 이름 강제 지정 가능함.


class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = models.TextField()
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    # 이렇게 해야 서버에서 파일을 찾아오는 시간을 단축할 수 있음. blank=True <- 해당 필드는 필수 항목은 아니라는 뜻
    file_upload = models.FileField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    # head_image는 이미지, file_upload는 파일을 가져오는 것.
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  # 시간 자동으로 저장되게 하기.
    # author: 추후 작성 예정

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    # null=True -> null값이 들어가도 된다는 의미 / on_delete=SET_NULL은 삭제된 정보는 null로 처리함 이때 null=True로 되어있어야함
    # on_delete=models.CASCADE # 정보 싹다 삭제

    # category는 일대다 관계일때 사용했음
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    # tag는 다대다 관계임. -> ForeignKey가 아니라 ManyToManyField로 해야함
    tags = models.ManyToManyField(Tag, blank=True)
    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]  # -1은 마지막 인덱스 ex) txt / xlsx / docx


class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE) # 혼자 해야돼서 일대다 관계여서 foreignkey로 함.
    author=models.ForeignKey(User,on_delete=models.CASCADE) # 혼자 해야돼서 일대다 관계여서 foreignkey로 함.
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}' # 현재글 이므로 해당 페이지+ #(anchor)id 이다.

blog/forms.py
from .models import Comment
from django import forms
class CommentForm(forms.ModelForm):
    class Meta:       # ModelForm에서 상속받은 경우에 있어야함
        model=Comment # field 5개인데 content하나만 사용 나머지는 다 결정되어있음.
        fields=('content',)
        # views에 formdetail로 이동후 -> post_detail에서 comment_form가능

blog/views.py
# context를 넣어서 보내는 건 views.py!
from django.db.models import Q
from django.shortcuts import render, redirect
from .models import Post, Category, Tag
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from .forms import CommentForm, Comment
from django.shortcuts import get_object_or_404  # db에서 하나만 가져오는 명령어


# Create your views here.

# CBV
class PostList(ListView):  # 그냥 안 돌아가서 urls 파일로 가서 바꿔야 함
    model = Post  # post_list
    ordering = '-pk'  # 최신 글부터 보이게 함
    paginate_by = 2  # 한페이지에 몇개씩 보여줄지 결정함

    # template_name = 'blog/index.html' #템플릿 name을 정의하지 않으면 클래스 명을 파일 이름으로 바꿔서 자동으로 찾음
    # 1.내가 이름을 바꿔서 지정하거나, 자동으로 연결되는 이름으로 다른 걸 바꾸던가(우린 후자)
    # template_name = 'blog/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()  # post_list를 가져옴 # 상위에서 가져오기때문
        context['categories'] = Category.objects.all()  # Category DB의 내용
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()  # category가 없을수 있기때문에 no_category이고 뒤에는 없는것 카운트
        return context  # => 리턴은 post_list.html로 들어가게된다.


# FBV
# == 위 클래스 이용하는 거랑 같음. 아래는 직접 코드를 써서 하는 방법
# def index(request):
#     posts = Post.objects.all().order_by('-pk')  # -사용시 내림차순, 없을시 오름차순 pk는 primary key의 약자를 의미함
#
#     return render(
#         request,
#         'blog/post_list.html',
#         {
#             'posts': posts,
#         }
#     )

class PostDetail(DetailView):
    model = Post

    # template_name='blog/single_post_page.html'
    # 여기는 템플릿 이름을 정의하지 않아서, 자동으로 post.html?을 자동으로 찾음
    # template_name = post_form.html  #post_detail.html로 이름 바꿔서 주석처리하면 자동으로 이름 바뀜

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()  # post_list를 가져옴 # 상위에서 가져오기 때문
        context['categories'] = Category.objects.all()  # Category DB의 내용
        context['no_category_post_count'] = Post.objects.filter(
            category=None).count()  # category가 없을 수 있기 때문에 no_category
        # 필터: 검색 조건, count 몇 개가 들어있는지 세는 것
        context['comment_form'] = CommentForm
        return context  # => 리턴은 post_detail.html로 들어가게 된다. (post.categories,no_category_post_count) 값이 넘어가게 됨.


def category_page(request, slug):  # 프로그래밍, 문화-예술, 웹개발, 미분류 -> no_category로 가게됌
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)  # post_list = Post.objects.all()이었다면 모든 리스트가 다 나옴
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'blog/post_list.html',
        {  # context 넣는 위치! 알기 '변수명 : 들어갈 내용'
            # 필터링한 것만 뜨게 하기
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        }
    )


# /blog/create_post/
class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):  # form
    # UserPassesTestMixin : 특정 사용자만 접근을 허용하기

    model = Post  # CreateView임
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']

    # template_name=post_form.html

    def test_func(self):  # UserPassesTestMixin에서 확인할 조건 : 최고권한(super user) 혹은 스태프(staff) 인 경우
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):  # CreateView에서 생성된 form이 제대로 입력되었는지 확인하는 함수
        current_user = self.request.user
        # 로그인을 했느냐 and 스태프나 관리자 계정이냐 (필요에 따라 하나 지워도 됨)
        if (current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser)):
            form.instance.author = current_user
            # not tag
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')  # 강제적으로 '/blog/'로 보내버림


# 토큰이 검증이 안 될 때 함수 실행 #관리자가 아닌 사용자한테 굳이 메시지를 띄울 필요는 없음.
# 에러 메시지 안 띄우고 바로 이전 페이지로 가게 하기
def crsf_failure(request, reason=""):
    return redirect('/blog/')


# blog/update_post/pk/
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']

    # post_form.html이 기본 템플릿. 그래서 edit 버튼 누르면 create new post 템플릿과 공유를 하게 됨. 수정 화면인데 생성 포스트 화면으로 뜸
    # -> 똑같은데 다른 템플릿을 만들고, 다른 템플릿 이름을 쓰면 됨.
    # post_form.html 복붙하고 이름 바꾸기
    template_name = "blog/post_update_form.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:  # 현재 화면에 보이는 포스트 글이 가져와짐
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied  # 에러 404

    # def single_post_page(request, pk):
    #     post = Post.objects.get(pk=pk) # objects.get은 괄호안에 만족하는 레코드를 가져오라는 의미이다.
    #
    #     return render(
    #         request,
    #         'blog/index.html',
    #         {
    #             'post':post,
    #         }
    #     )


def new_comment(request, pk):
    if request.user.is_authenticated:  # 댓글은 로그인 됐을 때만 작성 가능
        post = get_object_or_404(Post, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST)  # 댓글 작성하는 폼
            if comment_form.is_valid():  # 이 폼이 정상적이라면
                comment = comment_form.save(commit=False)  # 임시저장
                comment.post = post  # 현재 포스트
                comment.author = request.user  # 현재 user(로그인 된) #modify는 자동으로 save
                comment.save()  # save된 걸 불러옴?
                return redirect(comment.get_absolute_url())  # 이 포스트로 돌아가라

        else:
            return redirect(post.get_absolute_url())  # 주소에 바로 /new_comment/ 쳤을 땐 blog 페이지로 이동할 수 있도록
    else:  # 로그인 안 됐을 땐 권한이 없다고 할 것임.
        raise PermissionDenied


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment  # 자동으로 댓글 수정 폼에 내용 채워라?
    form_class = CommentForm

    # comment_form.html -> 이걸 자동으로 찾음. 안 만들면, 못 찾는다고 에러 뜸!

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


# class PostList(ListView): model=Post(Post.objects.all) post는 모두 불러오는것 내포하고있음 => post_list.html
# def get_queryset(self):
#       post_list=Post.objects.all  이렇게됌.
class PostSearch(PostList):  # post_list.html
    paginated_by = None  # pagination 안하겠다

    def get_queryset(self):  # Post(Post.objects.all) 이게 불러와진다
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search:{q}({self.get_queryset().count()})'

        return context

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}  <!-- static 폴더를 사용하겠다 -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel= "stylesheet" href = "{% static 'blog/bootstrap4/css/bootstrap.min.css' %}"> <!-- 여기를 참조 고정되서 사용 -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/a506b963cb.js" crossorigin="anonymous"></script> <!-- 폰트 -->
</head>
<body>

    {% include 'blog/nav.html' %}

    <div class="container my-4"> <!-- 마진을 의미, 위 아래에 중간 정도의 크기 mt(위), mb(아래), ml(오른쪽), mr(오른쪽) -->
        <!-- mx(수평), my(수직) -->
        <div class = "row">
            <div class = "col-sm-8" id="main-area">
            {% block main_area %}

            {% endblock %}
            </div>

            <!-- Side widget trim -> 공백제거-->
            <div class = "col-sm-4">
                <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input id="search-input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button onclick="searchPost();" class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4" id = 'categories-card'>
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <!-- post_list(post), categories, no_category_post_count -->

                                    <ul> <!-- categories -->
                                        {% for category in categories %}
                                        <li>
                                            <a href = "{{ category.get_absolute_url }}">
                                                {{ category }} ({{category.post_set.count}})
                                            </a>
                                        </li>
                                        {% endfor %}
                                        <li>
                                            <a href = "/blog/category/no_category/">
                                                미분류 ({{no_category_post_count }})
                                            </a>
                                        </li>
                                    </ul>
                            </div>
                        </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>

    {% include 'blog/footer.html' %}

    <script>
        function searchPost(){
            let searchValue = document.getElementById("search-input").value.trim();
            if(searchValue.length > 1) {
                location.href = "/blog/search/"+ searchValue + "/";
            }
            else {
                alert("검색어(" + searchValue + ")가 너무 짦습니다.");
            }
        };

        document.getElementById("search-input").addEventListener("keyup", function(event){
            if(event.key === 'Enter'){
                searchPost();
            }
        });
    </script>

</body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %} <!-- static 폴더를 사용하겠다 -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}"> <!-- 여기를 참조 고정되서 사용 -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
            integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
            crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/a506b963cb.js" crossorigin="anonymous"></script> <!-- 폰트 -->
</head>

<body>
{% include 'blog/nav.html' %}

<div class="container my-4"> <!-- 마진을 의미, 위 아래에 중간 정도의 크기 mt(위), mb(아래), ml(오른쪽), mr(오른쪽) -->
    <!-- mx(수평), my(수직) -->
    <div class="row">
        <div class="col-sm-12" id="main-area">
            {% block main_area %}

            {% endblock %}
        </div>
    </div>
</div>

{% include 'blog/footer.html' %}
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}

{% load crispy_forms_tags %} <!-- crispy bootstrap4 적용-->

  {% block head_title %}
      Edit Comment -Blog
  {% endblock %}
    {% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}

            {{form | crispy}}

        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {% endblock %}

blog/templates/blog/footer.html
      <!-- Footer-->
      <footer class="py-5 bg-dark"> <!-- padding -->
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
    </footer>

blog/templates/blog/index.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    <p>장고 연습하는 페이지입니다.</p>
    <!-- for문을 사용할때에는 처음 for문 사용하며 나중에 endfor  해주면되며 그 사이에 반복할 내용 넣기 -->
    {% for p in post_list %}
    <hr/>
    <h2><a href="{{p.get_absolute_url}}">{{p.title}}</a></h2>
    <h4>이 부분은 created_at    {{p.created_at}}</h4>
    <p>이 부분은 updated_at  {{p.updated_at}}</p>
    <p>{{p.content}}</p>

    {% endfor %}
</body>
</html>























<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport"-->
<!--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">-->
<!--    <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--    <title>{{post.title}} - Blog</title>-->
<!--</head>-->
<!--<body>-->
<!--    <nav>-->
<!--      <a href="/blog/">Blog</a>-->
<!--    </nav>-->
<!--    <h1>{{post.title}}</h1>-->
<!--    <h4>{{post.created_at}}</h4>-->
<!--    <p>{{post.content}}</p>-->
<!--    <hr/>-->
<!--    <h3>여기는 댓글이 들어올 자리입니다.</h3>-->
<!--</body>-->
<!--</html>-->

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ post.title }} - Blog
{% endblock %}

{% block main_area %}

<!-- Post content-->
<article>
    <div id="post-area">
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
            <h5 class="text-muted">{{ post.hook_text }}</h5>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">Posted on {{ post.created_at }}
                by <a href="#">{{ post.author | lower }}</a></div>

            <!-- edit button -->
            {% if user.is_authenticated and user == post.author %}
            <a class="btn btn-info btn-sm float-right" href="/blog/update_post/{{post.pk}}" role="button">
                <i class="fas fa-pen"></i>&nbsp;&nbsp;Edit Post
            </a>
            {% endif %}
            <!-- Post categories-->
            {% if post.category %}
            <span class="badge badge-secondary">{{post.category}}</span>
            {% else %}
            <span class="badge badge-secondary">미분류</span>
            {% endif %}
        </header>
        <!-- Preview image figure-->
        <figure class="mb-4">
            {% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head image"/>
            {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/800/200" alt="random image"/>
            {% endif %}
        </figure>
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">{{ post.content | linebreaksbr }}</p> <!-- linebreaksbr 은 엔터 기능 -->
            {% if post.tags.exists %}
            <i class="fas fa-tags"></i>
            {% for tag in post.tags.all %}
            <span class="badge badge-pill badge-light">{{tag}}</span>
            {% endfor %}
            <br/><br/>
            {% endif %}

            {% if post.file_upload %}
            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>Download:
                {% if post.get_file_ext == 'csv' %}
                <i class="fas fa-file-cvs"></i>
                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                <i class="fas fa-file-excel"></i>
                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                <i class="fas fa-file-word"></i>
                {% else %}
                <i class="fas fa-file"></i>
                {% endif %}
                {{ post.get_file_name }}
            </a>
            {% endif %}
        </section>
    </div>
</article>

<!-- Comments section-->
<section class="mb-5">
    <div id="comment-area">
        <!-- Comment form-->
        <div class="card bg-light">
            <div class="card-header">Leave a Comment</div>
            <div class="card-body">

                <!-- 로그인 됐으면 댓글 작성 form을 보여주고, 안 되어 있으면 로그인하라는 버튼을 띄워라 -->
                {% if user.is_authenticated %}
                <!-- 댓글 작성하는 부분 -->

                <!-- forms.py의 클래스와 views.py의 PostDetail에서 가져옴 -->
                <form class="mb-4" id="comment-form" method="POST"
                      action="{{ post.get_absolute_url }}new_comment/">
                    {% csrf_token %} <!-- 장고 폼에서는 이걸 붙여야 함. 항상 만들어서 같이 가도록 해야 넘겨줌 -->
                    <div class="form-group">
                        {{ comment_form | crispy }} <!-- views.py에서 class PostDetail의
                                                                     context['comment_form'] = CommentForm 이걸 띄움-->
                    </div>

                    <button type=submit class="btn btn-primary float-right">Submit</button>
                </form>


                {% else %} <!-- -->
                <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                   href="#" data-toggle="modal" data-target="#loginModal">Log In and leave a comment</a>
                {% endif %}
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                {% if post.comment_set.exists %}
                {% for comment in post.comment_set.iterator %}
                <!-- Single comment-->
                <div class="d-flex mb-4">
                    <div class="flex-shrink-0"><img class="rounded-circle"
                                                    src="https://dummyimage.com/50x50/ced4da/6c757d.jpg&text={{comment.author}}"
                                                    alt="..."/>
                    </div>
                    <div class="ms-3"> <!-- <div class="media-body"> -->
                        {% if user.is_authenticated and comment.author == user %}
                        <div class="float-right">
                            <a role="button" class="btn btn-sm btn-info" id="comment-{{comment.pk}}-update-btn"
                               href="/blog/update_comment/{{comment.pk}}/">
                                <small>edit</small></a>
                            <a role="button" class="btn btn-sm btn-danger" id="comment-{{comment.pk}}-delete-btn"
                               href="/blog/delete_comment/{{comment.pk}}/">
                                <small>delete</small></a>
                        </div>
                        {% endif %}
                        <div class="fw-bold">{{comment.author.username}} &nbsp;&nbsp;<small class="text-muted">{{comment.created_at}}</small>
                        </div>
                        <div>{{comment.content | linebreaks}}</div>
                        {% if comment.created_at != comment.modified_at %}
                        <p class="text-muted float-right"><small>Updated:{{comment.modified_at}}</small></p>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base_full_width.html' %}

{% load crispy_forms_tags %} <!-- crispy bootstrap4 적용-->

  {% block head_title %}
      Create Post - Blog
  {% endblock %}
    {% block main_area %}
    <h1>Create New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}

            {{form | crispy}}

        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {% endblock %}